### ISSUE TITLE
Question, multi currency, multi location.

### ISSUE THREAD

**Issue by alvin101** [rhomicom-systems-tech-gh/Rhomicom-ERP-Web#3]
I read the read me, but I see no mention of multi currency, multi location.

Will your system support these features?

**Comment by richardamensah** [comment]
Sure Alvin, [the published desktop version of the ERP](https://github.com/rhomicom-systems-tech-gh/Rhomicom-ERP-Desktop) already supports multiple currencies and multi location.
There's even a section in the accounting module for downloading exchange rates from the Internet before modifying them to suite one's needs as seen in the screen shots.

The web version will also do same when completed.
The same concept in the desktop is being carried over to the responsive web version.
Thanks
![accounting2](https://cloud.githubusercontent.com/assets/21276843/24072694/bd414cc4-0be2-11e7-96b8-bbdc2501e2d5.png)
![accounting1](https://cloud.githubusercontent.com/assets/21276843/24072695/bd43c49a-0be2-11e7-9700-1b279061062f.png)
